### ISSUE TITLE
Varying results using same code

### ISSUE THREAD

**Issue by LuRoe7** [easystats/correlation#101]
First of all also thank you from my side for the correlation package...makes things a lot more convenient! Could even make my statistics lecturer happy by showing him this function ;)

One thing I noticed:
I´m doing Bayesian correlation analysis on partialized data and the results (rho, the corresponding HDIs, ROPE and PD) differ very slightly when I run the code several times, although I´m leaving the code unchanged. What can be the reason for that? Is it a rounding issue?

Thanks in advance!

**Comment by DominiqueMakowski** [comment]
Hi @LuRoe7, welcome to github and thanks for the comment.

I think the reason why Bayesian analyses gives slightly different results is because of the "random" sampling that is inherent to how Bayes works. One way of fixing that is to run `set.seed(123)` before the correlation, so that R uses the same "random" generator. Let me know if that helps

**Comment by LuRoe7** [comment]
Yes works, if you run it every time before the correlation. Thank you for your quick reply and help! 👍 :)
