### ISSUE TITLE
Add directional hypothesis to cor_to_p() and cor_to_ci()

### ISSUE THREAD

**Issue by baranovskypd** [easystats/correlation#116]
Could you please add the ability to calculate p-value and CI for directional hypothesis tests with `cor_to_p()` and `cor_to_ci()`, where one can specify the `alternative` argument that takes values `"two.sided"`, `"greater"` or `"less"`? E.g.: `alternative = "greater"`

**Comment by DominiqueMakowski** [comment]
for [cor_to_p](https://github.com/easystats/correlation/blob/master/R/cor_to_p.R), that would essentially divide the end value by 2. But for [cor_to_ci](https://github.com/easystats/correlation/blob/master/R/cor_to_ci.R) I'm not entirely sure how to implement that 🤔 any ideas?

**Comment by DominiqueMakowski** [comment]
*bump* maybe @mattansb ?


(and kudos @baranovskypd for for the awesome post ☺️)

**Comment by mattansb** [comment]
It would look something like this:
```R
if (alternative == "greater") {
  alpha <- ci
  upper <- qnorm(alpha)
  CI <- c(-1, upper)
  
  p_val <- pnorm(r, lower.tail = FALSE)
} else if (alternative == "less") {
  alpha <- 1 - ci
  lower <- qnorm(alpha)
  CI <- c(lower, 1)
  
  p_val <- pnorm(r, lower.tail = TRUE)
}
```

Replace `pnorm` and `qnorm` with however you compute the normal CI and p value.

**Comment by baranovskypd** [comment]
> _bump_ maybe @mattansb ?
> 
> (and kudos @baranovskypd for for the awesome post )

Thank you for addressing this and for liking my post. You are doing a great job with `easystats` btw, really like the idea!

**Comment by DominiqueMakowski** [comment]
Adding `atlernative="greater"` or such to frequentist pearson works, though it's currently through piping the argument down to cor.test. This means that the correction isn't apply to stuff not computed in cor.test, like CIs for kendall & spearman 😕 

The problem is that we might need a general syntax for that in easystats, like could this technically apply to all p-values (even for parameters from regression models?) Also I find `alternative=c("two.sided", "greater", "less")` not the most intuitive, but I'm not sure what would be good alternatives for naming scheme 🤔 

Also, we would need to adapt @mattansb 's formula to [the different CIs algorithms](https://github.com/easystats/correlation/blob/master/R/cor_to_ci.R), not even mentioning the issue of post-adjusting them for methods in which they are natively computed (for instance by other packages). 

I'm not sure how important this feature is, too, like how much people actually use one-sided p-values, given the fire the thresholds are already under

**Comment by mattansb** [comment]
A perhaps a more simple method for what I suggested would make this look more do-able?

```R
p_val <- p_value(x)

if (alternative %in% c("greater", "less")) {
  ci_values <- ci(x, ci = 1 - 2 * alpha)
  
  if (alternative == "greater") {
    CI <- c(-1, ci_values$CI_high)
    p_val <- if (r > 0) p_val/2 else 1 - p_val/2
  } else {
    CI <- c(ci_values$CI_low, 1)
    p_val <- if (r < 0) p_val/2 else 1 - p_val/2
  }
}
```

**Comment by DominiqueMakowski** [comment]
that's indeed clearer and more doable 😅 

still, I wonder whether we should have such two-sided -> one-sided "converter" in base insight... I feel like it might be useful elsewhere right? @strengejacke what do you think?

**Comment by strengejacke** [comment]
would fit more into _parameters_, I'd say. It's not a model info / property per se that's being extracted here.

**Comment by DominiqueMakowski** [comment]
agree

**Comment by mattansb** [comment]
> I wonder whether we should have such two-sided -> one-sided "converter" in base insight...

This is only trivial for p-values, not for CIs...

**Comment by DominiqueMakowski** [comment]
but in your code chunk you make it look trivial for CIs too ^^
