### ISSUE TITLE
incorrect and non adjusted p values 

### ISSUE THREAD

**Issue by usernik1** [easystats/correlation#195]
It looks like when calculating a correlation with correlation::correlation( ..., method = "pearson", p_adjust = "bonferroni", ...) the p value is not adjusted and is also calculated too high by a factor of 10! Could this issue be fixed soon?

**Comment by bwiernik** [comment]
Can you please give a reproducible example?

**Comment by bwiernik** [comment]
The p values are being adjusted on my end. Note that psych appears to have a bug in `corr.test()` when both `x` and `y` data are specified. The values for `p` and `p.adj` are flipped. 

``` r
dat <- psychTools::bfi |> subset(select = c(1:5, 28)) |> na.omit()

correlation::correlation(dat[,1:5], 
                         dat[,6, drop = FALSE],
                         p_adjust = "bonferroni")[,c("Parameter1", "p")] |> 
  as.data.frame()
#>    Parameter1            p
#> 5          A1 6.379873e-16
#> 9          A2 4.630160e-08
#> 12         A3 8.374284e-03
#> 14         A4 1.097445e-12
#> 15         A5 9.980058e-10
correlation::correlation(dat[,1:5], 
                         dat[,6, drop = FALSE],
                         p_adjust = "none")[,c("Parameter1", "p")] |> 
  as.data.frame()
#>    Parameter1            p
#> 5          A1 4.253249e-17
#> 9          A2 3.086773e-09
#> 12         A3 5.582856e-04
#> 14         A4 7.316297e-14
#> 15         A5 6.653372e-11

# note that in psych::corr.test() currently, p.adj and p are flipped when `y` data is given
dat <- psychTools::bfi |> subset(select = c(1:5, 28)) |> na.omit()
psych::corr.test(dat[,1:5], dat[,6, drop = FALSE], adjust = "bonferroni")$p
#>             age
#> A1 2.126624e-16
#> A2 1.543387e-08
#> A3 2.791428e-03
#> A4 3.658148e-13
#> A5 3.326686e-10
psych::corr.test(dat[,1:5], dat[,6, drop = FALSE], adjust = "bonferroni")$p.adj
#>             age
#> A1 4.253249e-17
#> A2 3.086773e-09
#> A3 5.582856e-04
#> A4 7.316297e-14
#> A5 6.653372e-11
psych::corr.test(dat[,1:5], dat[,6, drop = FALSE], adjust = "none")$p
#>             age
#> A1 4.253249e-17
#> A2 3.086773e-09
#> A3 5.582856e-04
#> A4 7.316297e-14
#> A5 6.653372e-11
```

<sup>Created on 2021-06-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>


Note that `correlation::correlation()` is currenty overcorrecting for all of the combinations of variables in the full x and y tables, rather than in just the ones specified

One other comment: It is best to use `"holm"` (the default) rather than `"bonferroni"`, as the Holm adjustment dominates Bonferroni (is always more powerful) while have the same effect on Type 1 error rates. From the `?p.adjust` help in R:

> The first four methods are designed to give strong control of the family-wise error rate. There seems no reason to use the unmodified Bonferroni correction because it is dominated by Holm's method, which is also valid under arbitrary assumptions.
