### ISSUE TITLE
CRAN checks

### ISSUE THREAD

**Issue by strengejacke** [easystats/correlation#208]
https://cran.r-project.org/web/checks/check_results_correlation.html

Is this temporary, or is a fix needed?

**Comment by DominiqueMakowski** [comment]
Related to datawizard reorganization i think

**Comment by DominiqueMakowski** [comment]
ah no wait let me check

**Comment by DominiqueMakowski** [comment]
On current version no errors
```
== Results ===================================================================================
Duration: 11.0 s

[ FAIL 0 | WARN 13 | SKIP 0 | PASS 147 ]
```

**Comment by IndrajeetPatil** [comment]
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_correlation.html>.

Please correct before 2021-09-02 to safely retain your package on CRAN.

Note that this will be the *final* reminder.

**Comment by IndrajeetPatil** [comment]
@bwiernik Can you please take of this since you will be maintaining this package now? 

Once you submit the revised version, I will get an email to confirm the change of maintainership. 

Also, please remember to make a note of this in CRAN comments `.md` file since this change will leave a NOTE in R CMD CHECK.

**Comment by bwiernik** [comment]
Yep

**Comment by bwiernik** [comment]
So the tests all pass for me, but the examples fail with the GitHub versions installed because of https://github.com/easystats/datawizard/commit/c0d3b09f046b708a644ebe6d58af0cb3c0ad7ffc

Can someone help me understand next steps and sequences? Do I need to wait for see 0.6.5 to get onto CRAN? What's the status of that?

**Comment by strengejacke** [comment]
I think _see_ is ready to be submitted. I'll do this the next days.

**Comment by IndrajeetPatil** [comment]
Daniel, did you see our Twitter conversation?

@DominiqueMakowski Is this a good idea? Or do we need to wait for another release of {datawizard} with the visualization recipe function removed?

**Comment by strengejacke** [comment]
We need a thread where all urgent updates are listed. _bayestestR_ has a deadline, I think _correlation_ as well. So we should focus on the pipeline to get these updates on CRAN, and I also think we should stop making such drastic breaking changes that stand in our way when we need to submit an update with deadlines to CRAN.

**Comment by strengejacke** [comment]
> and I also think we should stop making such drastic breaking changes

More concrete: We should first (re-)move functions when the package that received the new function is on CRAN, and the other packages that depend on this function is on CRAN as well. After that, we can remove a function from its original place.

**Comment by DominiqueMakowski** [comment]
> @DominiqueMakowski Is this a good idea? 

It *sounds* like a good idea in principle, because the plot.visualization_recipe is the (only) function that calls `see`, so having it here would make sense. But then indeed as Daniel says I lost track too of where we're at with the CRAN updates and I don't understand well enough circular dependencies, reexports and breaking tests to say if now if the right moment to move it... the question is I think, if we freeze the ecosystem as it is now on GH, and push everything to CRAN, would everything work? Locally I have everything updated and it seems to work, but then @bwiernik mentioned the failing of some of the plots

**Comment by bwiernik** [comment]
This commit @IndrajeetPatil made to datawizard GH a few days ago with the global variable breaks the plot() function entirely https://github.com/easystats/datawizard/commit/c0d3b09f046b708a644ebe6d58af0cb3c0ad7ffc. 

One of these three is needed to fix that:
1. Namespace as see::geoms_from_list()
2. Copy geoms_from_list() to datawizard
3. Move that plot.visualisation_recipe() method to see

geoms_from_list() I think is added in see 0.6.5, so namespacing would depend on that

**Comment by DominiqueMakowski** [comment]
3 is done, hope it fixed the issue

**Comment by strengejacke** [comment]
_see_ is on CRAN (including @DominiqueMakowski latest changes)

**Comment by bwiernik** [comment]
Okay great. Then the last thing we need before I can submit correlation is to submit *datawizard* to CRAN so that the S3 method for `plot.visualisation_recipe()` is removed from there.

**Comment by strengejacke** [comment]
But it's just a conflict, or is there any specific reason to submit _datawizard_ first?

**Comment by bwiernik** [comment]
Checks in correlation fail because both datawizard and see have the S3 method currently, and the incorrectly namespaced one in datawizard gets precedence

Unless there is a way to say "the S3 method from that package", but I don't think there is when we import both. 

In any event, the datawizard function needs to get removed from CRAN ASAP to avoid potential confusing breakage depending on which package users attach first

**Comment by bwiernik** [comment]
The function in datawizard should ideally have never made it to CRAN because it never worked as written.

**Comment by strengejacke** [comment]
ok, the only problem I see is that @IndrajeetPatil is currently on vacation / travelling, so I'm not sure how fast we can get datawizard on CRAN.

**Comment by DominiqueMakowski** [comment]
mmh maybe we can submit on his behalf saying it's an urgent bugfix and then he'll just have to validate through his email?

**Comment by IndrajeetPatil** [comment]
`datawizard` update is on CRAN.

**Comment by bwiernik** [comment]
Submitted to CRAN.

**Comment by bwiernik** [comment]
> We see: Check: examples, Result: NOTE Examples with CPU (user + system) or elapsed time  >  10s user system elapsed cor_smooth 9.41 0.79 10.22 Please reduce each example to less than 5 sec. Best, Uwe 

Should I just \dontrun{} this? It is only intermittent and on one system

**Comment by strengejacke** [comment]
Yes, I would do that.
