### ISSUE TITLE
`visualization_recipe()` completely break `plot()`

### ISSUE THREAD

**Issue by strengejacke** [easystats/correlation#214]
Examples from the [see-vignette](https://easystats.github.io/see/articles/correlation.html) no longer work:
``` r
library(correlation)
library(see)
data(iris)

result <- correlation(iris)
s <- summary(result)

plot(s, size_point = 2)
#> Error in .visualisation_easycormatrix_scale(which = "x_discrete", ...): unused argument (size_point = 2)
plot(s, type = "tile")
#> Error in .visualisation_easycormatrix_scale(which = "x_discrete", ...): unused argument (type = "tile")
plot(s, show_values = TRUE, show_p = TRUE, show_legend = FALSE)
#> Error in .visualisation_easycormatrix_scale(which = "x_discrete", ...): unused arguments (show_values = TRUE, show_p = TRUE, show_legend = FALSE)
```

<sup>Created on 2021-10-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bwiernik** [comment]
Okay, so the issue here is that the old plot method worked like the *parameters* plot methods--there were specific named arguments to control a specific set of aesthetics for certain geoms (e.g., `size_point` for point size). Now, with the visualisation_recipe approach, there are arguments for each geom (e.g., `point`) that take lists of aesthetic arguments.

The errors come because the various internal `.visualisation_easycormatrix_*()` functions don't have `...` arguments.

The question is how we want to reconcile. Four 
options

1. Ignore it. Have examples that work in the *correlation* docs
2. Add `...` to the internal functions so that they absorb the arguments from the examples, even if the result is not what was previously produced.
3. Be more careful about passing `...` around. Do we need to do that for these internal functions?
4. Add code to accommodate the previous arguments and adapt them to the new structure. 

Only (4) would ensure that the published code produces the expected results, but leaves some funky legacy code around inside the functions. Probably the best approach though. We should decide how we want to handle it here, as well as for any future packages that might be converted to visualisation_recipe() (e.g., if we every converted *parameters*, there would be a bunch of arguments running into this issue).

thoughts @DominiqueMakowski @IndrajeetPatil @strengejacke ?

**Comment by DominiqueMakowski** [comment]
I'd say 2 is a good compromise as it won't break stuff, and then people can check out the more precise way of having more control over some arguments...

**Comment by strengejacke** [comment]
``` r
library(correlation)
library(see)
data(iris)

result <- correlation(iris)
s <- summary(result)

plot(s, size_point = 26, type = "point")
```

![](https://i.imgur.com/fabnUut.png)

``` r
plot(s, type = "tile") # default
```

![](https://i.imgur.com/1A2bCZn.png)

``` r
plot(s, show_values = FALSE)
```

![](https://i.imgur.com/ngzkcGI.png)

``` r
plot(s, show_p = FALSE)
```

![](https://i.imgur.com/AfGYi38.png)

<sup>Created on 2022-01-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
what is missing, though, is the `show_legend` argument. Not sure where to best add this, maybe in the vis-recipe-scale-functions?

**Comment by DominiqueMakowski** [comment]
I tihnk we can have an exposed `show_legend` argument since we have arguments like `show_text` & `show_data`. I'm not sure how's the best way to implement it though wether add a theme(legend.position) layer or deactivate the guides within the respective layers?

**Comment by bwiernik** [comment]
Probably easiest to add `guide = ifelse(isFALSE(show_legend), "none", "legend")` to the individual layers
