### ISSUE TITLE
GGM color scheme

### ISSUE THREAD

**Issue by araikes** [easystats/correlation#268]
Hi,

I presume this should be easy but I'm just not finding it. Is there a way to change the color scheme for the GGM plots? Thanks.

**Comment by strengejacke** [comment]
@DominiqueMakowski any ideas?

**Comment by bwiernik** [comment]
Same way as for changing ggplot2 color scales generally. Add a `scale_edge_color_*()` function or a `scale_color_*(aesthetics = "edge_color")` function.

**Comment by DominiqueMakowski** [comment]
yes, since the output in that case is a [ggraph](https://github.com/thomasp85/ggraph) graph, one can modify the the aesthetic a posterior. Also, if you run `visualization_recipe()` instead of `plot()`, you should be able to see all the layers and the name of the arguments etc. (and you can even reproduce the plots directly in ggraph for more customization). Hope that helps

**Comment by IndrajeetPatil** [comment]
Here is a reprex. You should of course select more sensible colors.

``` r
library(see)
library(correlation)
library(ggraph)
#> Loading required package: ggplot2

plot(correlation(mtcars, partial = TRUE)) +
  scale_edge_color_continuous(low = "blue", high = "red")
```

![](https://i.imgur.com/vXM8ag5.png)

<sup>Created on 2022-09-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
