### ISSUE TITLE
Plot method for correlation matrix

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/correlation#44]
Should we add a plot method in see for a correlation matrix obtained via `summary()` or `as.table()`, similar to the one made in the [README](https://github.com/easystats/correlation/raw/master/man/figures/unnamed-chunk-7-1.png) using ggcorplot. Can we do it with raw ggplot to avoid having another (conditional) dependency?

**Comment by strengejacke** [comment]
Yes, probably similar to
https://strengejacke.github.io/sjPlot/reference/sjp.corr.html
https://github.com/strengejacke/sjPlot/blob/master/R/sjPlotCorr.R

I would then remove that function from sjPlot, to narrow the focus of the sjPlot-package, and because _correlation_ offers much more options anyway.
