### ISSUE TITLE
replace `as.table`?

### ISSUE THREAD

**Issue by mattansb** [easystats/correlation#68]
This seem problematic to me:

``` r
library(correlation)
cor <- correlation(iris)

class(as.table(cor))
#> [1] "easycormatrix" "data.frame"
```

(and not a `table`.)

I suggest changing `as.matrix.easycorrelation` in two ways:

1. Add a `redundant` argument (default `FALSE`?).
2. Add attributes that can be used by `print.easycormatrix` to give the same printing as is currently given?
    - Or have a argument of `stars` that when true returns a character matrix with the stars baked in?

**Comment by DominiqueMakowski** [comment]
and use as.matrix instead of as.table?

**Comment by mattansb** [comment]
Think so, yes.

**Comment by DominiqueMakowski** [comment]
The problem is that currently, as.matrix creates a *real* matrix, i.e., without the Parameter column. IT was originally meant to be easily used with all the packages/functions that expect a correlation matrix-like input (psych, ppcor ...)

On the other hand, tables are a very specific class in R, and most of the functions that creates "tables" (able, apa6_table and so on) do not create class tables but rather a "manuscript table". So I'm not sure how to best handle that 😕 

Basically, these are the possible representations of a correlation and the current accessors:

- Full long (one row per correlation): `correlation::correlation(iris, redundant = T)`  
- Long (one row per correlation): `correlation::correlation(iris)`  
- Triangular table of correlation matrix *(has n+1 columns compared to row because of the Parameter column)*: `summary(correlation::correlation(iris))`  
- Table of correlation matrix: : `summary(correlation::correlation(iris), redundant = T)`  OR `as.table(correlation::correlation(iris))`
- True matrix of correlation *(n cols & n rows, all populated)*:  `as.matrix(correlation::correlation(iris))`

**Comment by mattansb** [comment]
The only issue is that `as.table` is a *generic coercion function*, so the returned class should be `table`.

So we can either return a `table`, or use a different function name (e.g., `papaja` has `apa_table` to make "tables"). This can even be `as_table` (🤢 not a fan).

Alternatively, this can be part of the printing method of the original "long" correlation data frame:

```R
print.easycorrelation <- function(x, table = FALSE, ...) {
  if (table) {
    .as.table(x) # now an internal function
  } else {
    NextMethod() # as has class "parameters_model"
  }
}
```

**Comment by DominiqueMakowski** [comment]
We could simply remove `as.table()`, as it is just a shortcut for `summary(..., redundant=T)`, but we'd need to deprecate it first.

**Comment by mattansb** [comment]
Sounds good 👍

**Comment by strengejacke** [comment]
Note that `as.table()` works for plotting, while `as.matrix()` does not.

**Comment by strengejacke** [comment]
https://easystats.github.io/see/articles/correlation.html
