### ISSUE TITLE
upper and lower matrix with different correlation coefficients

### ISSUE THREAD

**Issue by strengejacke** [easystats/correlation#74]
From https://github.com/strengejacke/sjPlot/issues/31:

Would be nice if sjt.corr could display different correlation coefficients in the upper and lower triangle of the matrix. I think it is quite common to display Pearson and Spearman correlation coefficients and to do this in one matrix.

lower.tri(x, diag = FALSE) and upper.tri(x, diag = FALSE) might come in handy as mentioned here:
http://www.sthda.com/english/wiki/elegant-correlation-table-using-xtable-r-package

**Comment by DominiqueMakowski** [comment]
I was certain I answered that 🤔 

That is not really feasible due to to the way that correlation is made, as it needs the full and redundant matrix to switch between matrices and "long" tables.

That being said @helix123, it can easily be done manually as follows:

``` r
library(correlation)

m <- as.matrix(correlation(iris))
m_spear <- as.matrix(correlation(iris, method="spearman"))

m[upper.tri(m)] <- m_spear[upper.tri(m_spear)] 

m
#>              Sepal.Length Sepal.Width Petal.Length Petal.Width
#> Sepal.Length    1.0000000  -0.1667777    0.8818981   0.8342888
#> Sepal.Width    -0.1175698   1.0000000   -0.3096351  -0.2890317
#> Petal.Length    0.8717538  -0.4284401    1.0000000   0.9376668
#> Petal.Width     0.8179411  -0.3661259    0.9628654   1.0000000
```

<sup>Created on 2020-05-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
