### ISSUE TITLE
Confidence Intervals for Spearman's correlation

### ISSUE THREAD

**Issue by TarandeepKang** [easystats/correlation#80]
I am aware of two methods for the calculation of confidence intervals for a Spearman correlation. 

Bootstrap- eg using the spearmanRho function in the rcompanion package

Jackknife using https://cran.r-project.org/web/packages/spearmanCI/spearmanCI.pdf 

Others were discussed in our recent Twitter thread. I am happy to help with the implementation in any way I can.

**Comment by tsbaguley** [comment]
I'm not convinced that bootstrap CIs are ideal here. Using the Fisher z transformation is traditional. However, it turns out that this has weaknesses. I've coded up a few approaches here:

https://rpubs.com/seriousstats/616206

This includes a CI for tau based on Fieller et al. (1957) and several approaches for rho based on Fieller et al. Bonett & Wright (2000) and Bishara & Hittner (2017). In principle the rank approach might also work for tau but I haven't seen any simulations for that.

**Comment by DominiqueMakowski** [comment]
@tsbaguley that's very helpful. Do you mind if we use this for this package?

**Comment by tsbaguley** [comment]
Not at all - please do.

**Comment by DominiqueMakowski** [comment]
@TarandeepKang it has been added, please do try it out :) 

Thanks again @tsbaguley, do not hesitate to double-check if the implementation is okay!

**Comment by TarandeepKang** [comment]
That is fantastic! Thank you very much indeed! Which of @tsbaguley's did did you implement in the end? Just so I know which citations to provide in my paper. :) Again, thank you to everyone involved!

**Comment by DominiqueMakowski** [comment]
by default it uses Fieller et al., 1957 's correction (as per Bishara and Hittner, 2017), but it can be overridden by setting `correction='bw'` or `correction='none'`

**Comment by TarandeepKang** [comment]
Something strange has happened.  I checked for any updates using the GitHub install command, and they appear to have lost access to these features.
